// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var alloc, get_klass, web_service;



  web_service = require('./web_service');

  get_klass = function(type) {
    var err, klass;
    err = klass = null;
    klass = (function() {
      switch (type) {
        case "web_service_binding.twitter":
          return web_service.TwitterBinding;
        case "web_service_binding.github":
          return web_service.GithubBinding;
        case "web_service_binding.keybase":
          return web_service.KeybaseBinding;
        default:
          err = new Error("Unknown proof class: " + type);
          return null;
      }
    })();
    return [err, klass];
  };

  alloc = function(type, args) {
    var err, klass, ret, _ref;
    ret = null;
    _ref = get_klass(type), err = _ref[0], klass = _ref[1];
    if (klass != null) {
      ret = new klass(args);
    }
    return ret;
  };

  exports.get_klass = get_klass;

  exports.alloc = alloc;

}).call(this);
