// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Base, KCP, Message, SHA256, Verifier, WordArray, akatch, base64u, bufeq_secure, constants, decode, iced, json_stringify_sorted, katch, kbpgp, make_esc, make_ids, sha256, streq_secure, triplesec, unix_time, util, __iced_k, __iced_k_noop, _ref;

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  kbpgp = require('kbpgp');

  constants = require('./constants').constants;

  KCP = kbpgp["const"].openpgp;

  _ref = kbpgp.util, katch = _ref.katch, akatch = _ref.akatch, bufeq_secure = _ref.bufeq_secure, json_stringify_sorted = _ref.json_stringify_sorted, unix_time = _ref.unix_time, base64u = _ref.base64u, streq_secure = _ref.streq_secure;

  triplesec = require('triplesec');

  WordArray = triplesec.WordArray;

  SHA256 = triplesec.hash.SHA256;

  Message = kbpgp.processor.Message;

  decode = kbpgp.armor.decode;

  make_esc = require('iced-error').make_esc;

  util = require('util');

  sha256 = function(pgp) {
    return (new SHA256).bufhash(new Buffer(pgp, 'utf8'));
  };

  make_ids = function(pgp) {
    var hash, id, short_id;
    hash = sha256(pgp);
    id = hash.toString('hex');
    short_id = base64u.encode(hash.slice(0, constants.short_id_bytes));
    return {
      id: id,
      short_id: short_id
    };
  };

  Verifier = (function() {
    function Verifier(_arg, km, base) {
      this.pgp = _arg.pgp, this.id = _arg.id, this.short_id = _arg.short_id;
      this.km = km;
      this.base = base;
    }

    Verifier.prototype.verify = function(cb) {
      var esc, ret, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "Verifier::verfiy");
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/base.iced",
          funcname: "Verifier.verify"
        });
        _this._check_ids(esc(__iced_deferrals.defer({
          lineno: 34
        })));
        __iced_deferrals._fulfill();
      })(function() {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "src/base.iced",
            funcname: "Verifier.verify"
          });
          _this._parse_and_process(esc(__iced_deferrals.defer({
            lineno: 35
          })));
          __iced_deferrals._fulfill();
        })(function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/base.iced",
              funcname: "Verifier.verify"
            });
            _this._check_json(esc(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return ret = arguments[0];
                };
              })(),
              lineno: 36
            })));
            __iced_deferrals._fulfill();
          })(function() {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "src/base.iced",
                funcname: "Verifier.verify"
              });
              _this._check_expired(esc(__iced_deferrals.defer({
                lineno: 37
              })));
              __iced_deferrals._fulfill();
            })(function() {
              return cb(null, ret);
            });
          });
        });
      });
    };

    Verifier.prototype._check_ids = function(cb) {
      var err, id, short_id, _ref1;
      _ref1 = make_ids(this.pgp), short_id = _ref1.short_id, id = _ref1.id;
      err = !streq_secure(id, this.id) ? new Error("Long IDs aren't equal; wanted " + id + " but got " + this.id) : !streq_secure(short_id, this.short_id) ? new Error("Short IDs aren't equal: wanted " + short_id + " but got " + this.short_id) : null;
      return cb(err);
    };

    Verifier.prototype._check_expired = function(cb) {
      var err, expired, now;
      now = unix_time();
      expired = now - this.json.date - this.json.expire_in;
      err = expired > 0 ? new Error("Expired " + expired + "s ago") : null;
      return cb(err);
    };

    Verifier.prototype._parse_and_process = function(cb) {
      var eng, err, msg, ___iced_passed_deferral, __iced_deferrals, __iced_k, _ref1,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      err = null;
      _ref1 = decode(this.pgp), err = _ref1[0], msg = _ref1[1];
      if ((err == null) && (msg.type !== KCP.message_types.generic)) {
        err = new Error("wrong mesasge type; expected a generic message; got " + msg.type);
      }
      (function(__iced_k) {
        if (err == null) {
          eng = new Message(_this.km);
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/base.iced",
              funcname: "Verifier._parse_and_process"
            });
            eng.parse_and_process(msg.body, __iced_deferrals.defer({
              assign_fn: (function(__slot_1) {
                return function() {
                  err = arguments[0];
                  return __slot_1.literals = arguments[1];
                };
              })(_this),
              lineno: 69
            }));
            __iced_deferrals._fulfill();
          })(__iced_k);
        } else {
          return __iced_k();
        }
      })(function() {
        return cb(err);
      });
    };

    Verifier.prototype._check_json = function(cb) {
      var b, e, err, json, l, n, sw, ___iced_passed_deferral, __iced_deferrals, __iced_k, _ref1,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      err = json = null;
      if ((n = this.literals.length) !== 1) {
        err = new Error("Expected only one pgp literal; got " + n);
      } else {
        l = this.literals[0];
        _ref1 = katch((function() {
          return JSON.parse(l.data);
        })), e = _ref1[0], this.json = _ref1[1];
        if (e != null) {
          err = new Error("Couldn't parse JSON signed message: " + e.message);
        }
      }
      (function(__iced_k) {
        if (err == null) {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/base.iced",
              funcname: "Verifier._check_json"
            });
            _this.base._v_check({
              json: _this.json
            }, __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return err = arguments[0];
                };
              })(),
              lineno: 83
            }));
            __iced_deferrals._fulfill();
          })(function() {
            var _ref2;
            return __iced_k(err != null ? void 0 : (sw = (_ref2 = l.get_data_signer()) != null ? _ref2.sig : void 0) == null ? err = new Error("Expected a signature on the payload message") : (_this.km.find_pgp_key((b = sw.get_key_id()))) == null ? err = new Error("Failed sanity check; didn't have a key for '" + (b.toString('hex')) + "'") : void 0);
          });
        } else {
          return __iced_k();
        }
      })(function() {
        return cb(err, _this.json);
      });
    };

    return Verifier;

  })();

  Base = (function() {
    function Base(_arg) {
      this.km = _arg.km;
    }

    Base.prototype._v_check = function(obj, cb) {
      return cb(null);
    };

    Base.prototype.json = function(_arg) {
      var body, date, expire_in, out, seqno, tag;
      tag = _arg.tag, expire_in = _arg.expire_in, body = _arg.body, seqno = _arg.seqno;
      expire_in || (expire_in = constants.expire_in);
      tag = constants.tags.sig;
      date = unix_time();
      out = {
        tag: tag,
        expire_in: expire_in,
        body: body,
        date: date
      };
      if (seqno != null) {
        out.seqno = seqno;
      }
      return out;
    };

    Base.prototype.generate = function(cb) {
      var err, id, json, out, pgp, short_id, signing_key, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      out = null;
      json = json_stringify_sorted(this.json());
      (function(__iced_k) {
        if ((signing_key = _this.km.find_best_pgp_key(KCP.key_flags.sign_data)) == null) {
          return __iced_k(err = new Error("No signing key found"));
        } else {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/base.iced",
              funcname: "Base.generate"
            });
            kbpgp.burn({
              msg: json,
              signing_key: signing_key,
              armor: true
            }, __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  err = arguments[0];
                  return pgp = arguments[1];
                };
              })(),
              lineno: 121
            }));
            __iced_deferrals._fulfill();
          })(function() {
            var _ref1;
            return __iced_k(err == null ? ((_ref1 = make_ids(pgp), short_id = _ref1.short_id, id = _ref1.id, _ref1), out = {
              pgp: pgp,
              json: json,
              id: id,
              short_id: short_id
            }) : void 0);
          });
        }
      })(function() {
        return cb(err, out);
      });
    };

    Base.prototype.verify = function(obj, cb) {
      var esc, ret, verifier, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "Base::verfiy");
      verifier = new Verifier(obj, this.km, this);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/base.iced",
          funcname: "Base.verify"
        });
        verifier.verify(esc(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return ret = arguments[0];
            };
          })(),
          lineno: 136
        })));
        __iced_deferrals._fulfill();
      })(function() {
        return cb(null, ret);
      });
    };

    return Base;

  })();

  exports.Base = Base;

}).call(this);
