// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Base, DoNotReset, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base').Base;

  constants = require('./constants').constants;

  exports.DoNotReset = DoNotReset = (function(_super) {
    __extends(DoNotReset, _super);

    function DoNotReset(obj) {
      DoNotReset.__super__.constructor.call(this, obj);
    }

    DoNotReset.prototype._type = function() {
      return constants.sig_types.do_not_reset;
    };

    DoNotReset.prototype._type_v2 = function() {
      return constants.sig_types_v2.do_not_reset;
    };

    return DoNotReset;

  })(Base);

}).call(this);
