// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Base, Eldest, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base').Base;

  constants = require('./constants').constants;

  exports.Eldest = Eldest = (function(_super) {
    __extends(Eldest, _super);

    Eldest.prototype._v_include_pgp_details = function() {
      return true;
    };

    Eldest.prototype._v_pgp_km = function() {
      return this.km();
    };

    function Eldest(obj) {
      this.device = obj.device;
      Eldest.__super__.constructor.call(this, obj);
    }

    Eldest.prototype._type = function() {
      return constants.sig_types.eldest;
    };

    Eldest.prototype._type_v2 = function() {
      return constants.sig_types_v2.eldest;
    };

    Eldest.prototype._optional_sections = function() {
      return Eldest.__super__._optional_sections.call(this).concat(["device"]);
    };

    Eldest.prototype._v_customize_json = function(ret) {
      if (this.device != null) {
        return ret.body.device = this.device;
      }
    };

    Eldest.prototype._v_require_eldest_kid = function() {
      return false;
    };

    return Eldest;

  })(Base);

}).call(this);
