// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Base, Login, bufeq_secure, constants, kbpgp, unix_time, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };



  kbpgp = require('kbpgp');

  Base = require('./base').Base;

  constants = require('./constants').constants;

  _ref = kbpgp.util, bufeq_secure = _ref.bufeq_secure, unix_time = _ref.unix_time;

  exports.Login = Login = (function(_super) {
    __extends(Login, _super);

    function Login(obj) {
      this.nonce = obj.nonce;
      Login.__super__.constructor.call(this, obj);
    }

    Login.prototype._type = function() {
      return constants.sig_types.login;
    };

    Login.prototype._json = function() {
      var ret;
      ret = Login.__super__._json.call(this, {
        expire_in: 24 * 60 * 60
      });
      ret.body.nonce = this.nonce ? this.nonce.toString('hex') : null;
      return ret;
    };

    return Login;

  })(Base);

}).call(this);
