// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Base, Masterkey, SubkeyBase, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base').Base;

  constants = require('./constants').constants;

  SubkeyBase = require('./subkey').SubkeyBase;

  exports.Masterkey = Masterkey = (function(_super) {
    __extends(Masterkey, _super);

    Masterkey.prototype.get_field = function() {
      return "masterkey";
    };

    Masterkey.prototype.get_new_key_section = function() {
      return this.masterkey;
    };

    Masterkey.prototype.set_new_key_section = function(m) {
      return this.masterkey = m;
    };

    Masterkey.prototype.get_new_km = function() {
      return this.masterkm;
    };

    Masterkey.prototype._type = function() {
      return constants.sig_types.masterkey;
    };

    Masterkey.prototype._type_v2 = function() {
      return constants.sig_types_v2.masterkey;
    };

    Masterkey.prototype.need_reverse_sig = function() {
      return true;
    };

    Masterkey.prototype._v_include_pgp_details = function() {
      return true;
    };

    Masterkey.prototype._required_sections = function() {
      return Masterkey.__super__._required_sections.call(this).concat(["masterkey"]);
    };

    function Masterkey(obj) {
      this.masterkey = obj.masterkey;
      this.masterkm = obj.masterkm;
      Masterkey.__super__.constructor.call(this, obj);
    }

    return Masterkey;

  })(SubkeyBase);

}).call(this);
