// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var Base, PGPUpdate, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base').Base;

  constants = require('./constants').constants;

  exports.PGPUpdate = PGPUpdate = (function(_super) {
    __extends(PGPUpdate, _super);

    function PGPUpdate() {
      return PGPUpdate.__super__.constructor.apply(this, arguments);
    }

    PGPUpdate.prototype._v_include_pgp_hash = function() {
      return true;
    };

    PGPUpdate.prototype._v_require_full_pgp_hash = function() {
      return true;
    };

    PGPUpdate.prototype._type = function() {
      return constants.sig_types.pgp_update;
    };

    return PGPUpdate;

  })(Base);

}).call(this);
