// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Base, Revoke, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };



  Base = require('./base').Base;

  constants = require('./constants').constants;

  exports.Revoke = Revoke = (function(_super) {
    __extends(Revoke, _super);

    function Revoke(obj) {
      this.revoke = obj.revoke;
      Revoke.__super__.constructor.call(this, obj);
    }

    Revoke.prototype._type = function() {
      return constants.sig_types.auth;
    };

    Revoke.prototype._json = function() {
      var ret;
      ret = Revoke.__super__._json.call(this, {});
      ret.body.revoke = this.revoke;
      return ret;
    };

    return Revoke;

  })(Base);

}).call(this);
