// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Base, SharedDHKey, SubkeyBase, constants, iced, __iced_k, __iced_k_noop,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  Base = require('./base').Base;

  constants = require('./constants').constants;

  SubkeyBase = require('./subkey').SubkeyBase;

  exports.SharedDHKey = SharedDHKey = (function(_super) {
    __extends(SharedDHKey, _super);

    SharedDHKey.prototype.get_field = function() {
      return "shared_dh_key";
    };

    SharedDHKey.prototype.get_new_key_section = function() {
      return this.shared_dh_key;
    };

    SharedDHKey.prototype.set_new_key_section = function(m) {
      m.generation = this.generation;
      return this.shared_dh_key = m;
    };

    SharedDHKey.prototype.get_new_km = function() {
      return this.shared_dh_km;
    };

    SharedDHKey.prototype._type = function() {
      return constants.sig_types.shared_dh_key;
    };

    SharedDHKey.prototype._type_v2 = function() {
      return constants.sig_types_v2.shared_dh_key;
    };

    SharedDHKey.prototype._v_include_pgp_details = function() {
      return true;
    };

    SharedDHKey.prototype._required_sections = function() {
      return SharedDHKey.__super__._required_sections.call(this).concat(["shared_dh_key"]);
    };

    SharedDHKey.prototype._v_check = function(_arg, cb) {
      var err, json, v, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      json = _arg.json;
      err = null;
      (function(_this) {
        return (function(__iced_k) {
          var _ref, _ref1;
          if (typeof (v = json != null ? (_ref = json.body) != null ? (_ref1 = _ref.shared_dh_key) != null ? _ref1.generation : void 0 : void 0 : void 0) !== 'number') {
            return __iced_k(err = new Error("Need shared_dh_key.generation to be an integer"));
          } else {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/proofs/src/shared_dh_key.iced",
                funcname: "SharedDHKey._v_check"
              });
              SharedDHKey.__super__._v_check.call(_this, {
                json: json
              }, __iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    return err = arguments[0];
                  };
                })(),
                lineno: 25
              }));
              __iced_deferrals._fulfill();
            })(__iced_k);
          }
        });
      })(this)((function(_this) {
        return function() {
          return cb(err);
        };
      })(this));
    };

    function SharedDHKey(obj) {
      this.shared_dh_key = obj.shared_dh_key;
      this.shared_dh_km = obj.shared_dh_km;
      this.generation = obj.generation;
      SharedDHKey.__super__.constructor.call(this, obj);
    }

    return SharedDHKey;

  })(SubkeyBase);

}).call(this);
