// Generated by IcedCoffeeScript 1.7.1-g
(function() {
  var Base, Subkey, SubkeyBase, a_json_parse, constants, iced, make_esc, pgp_utils, streq_secure, unix_time, __iced_k, __iced_k_noop, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  Base = require('./base').Base;

  constants = require('./constants').constants;

  make_esc = require('iced-error').make_esc;

  pgp_utils = require('pgp-utils');

  _ref = pgp_utils.util, unix_time = _ref.unix_time, streq_secure = _ref.streq_secure;

  a_json_parse = function(x, cb) {
    var e, err, ret;
    ret = err = null;
    try {
      ret = JSON.parse(x);
    } catch (_error) {
      e = _error;
      err = e;
    }
    return cb(err, ret);
  };

  exports.SubkeyBase = SubkeyBase = (function(_super) {
    __extends(SubkeyBase, _super);

    SubkeyBase.prototype.get_subkey = function() {
      return null;
    };

    SubkeyBase.prototype.get_subkm = function() {
      return null;
    };

    SubkeyBase.prototype.set_subkey = function(s) {};

    SubkeyBase.prototype.get_field = function() {
      return null;
    };

    SubkeyBase.prototype._v_generate = function(opts, cb) {
      var armored, eng, esc, msg, obj, reverse_sig, type, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "_v_generate");
      (function(_this) {
        return (function(__iced_k) {
          if ((_this.get_subkey() == null) && (_this.get_subkm() != null)) {
            reverse_sig = null;
            (function(__iced_k) {
              if (_this.get_subkm().can_sign()) {
                eng = _this.get_subkm().make_sig_eng();
                msg = {
                  ctime: unix_time(),
                  delegated_by: _this.km().get_ekid().toString('hex'),
                  uid: _this.user.local.uid,
                  username: _this.user.local.username
                };
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/max/src/keybase/proofs/src/subkey.iced",
                    funcname: "SubkeyBase._v_generate"
                  });
                  eng.box(JSON.stringify(msg), esc(__iced_deferrals.defer({
                    assign_fn: (function() {
                      return function() {
                        armored = arguments[0].armored;
                        return type = arguments[0].type;
                      };
                    })(),
                    lineno: 35
                  })));
                  __iced_deferrals._fulfill();
                })(function() {
                  return __iced_k(reverse_sig = {
                    sig: armored,
                    type: type
                  });
                });
              } else {
                return __iced_k();
              }
            })(function() {
              obj = {
                kid: _this.get_subkm().get_ekid().toString('hex'),
                reverse_sig: reverse_sig
              };
              if (_this.parent_kid != null) {
                obj.parent_kid = _this.parent_kid;
              }
              return __iced_k(_this.set_subkey(obj));
            });
          } else {
            return __iced_k();
          }
        });
      })(this)((function(_this) {
        return function() {
          return cb(null);
        };
      })(this));
    };

    SubkeyBase.prototype._json = function() {
      var ret;
      ret = SubkeyBase.__super__._json.call(this, {});
      ret.body[this.get_field()] = this.get_subkey();
      if (this.device != null) {
        ret.body.device = this.device;
      }
      return ret;
    };

    SubkeyBase.prototype._v_check = function(_arg, cb) {
      var a, b, eng, err, esc, json, payload, raw, sig, skm, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      json = _arg.json;
      esc = make_esc(cb, "SubkeyBase::_v_check");
      err = null;
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/proofs/src/subkey.iced",
            funcname: "SubkeyBase._v_check"
          });
          SubkeyBase.__super__._v_check.call(_this, {
            json: json
          }, esc(__iced_deferrals.defer({
            lineno: 55
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            var _ref1, _ref2, _ref3;
            if (((sig = json != null ? (_ref1 = json.body) != null ? (_ref2 = _ref1[_this.get_field()]) != null ? (_ref3 = _ref2.reverse_sig) != null ? _ref3.sig : void 0 : void 0 : void 0 : void 0) != null) && ((skm = _this.get_subkm()) != null)) {
              eng = skm.make_sig_eng();
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/proofs/src/subkey.iced",
                  funcname: "SubkeyBase._v_check"
                });
                eng.unbox(sig, esc(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return raw = arguments[0];
                    };
                  })(),
                  lineno: 59
                })));
                __iced_deferrals._fulfill();
              })(function() {
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/max/src/keybase/proofs/src/subkey.iced",
                    funcname: "SubkeyBase._v_check"
                  });
                  a_json_parse(raw, esc(__iced_deferrals.defer({
                    assign_fn: (function() {
                      return function() {
                        return payload = arguments[0];
                      };
                    })(),
                    lineno: 60
                  })));
                  __iced_deferrals._fulfill();
                })(function() {
                  if (!streq_secure((a = _this.km().get_ekid().toString('hex')), (b = payload.delegated_by))) {
                    err = new Error("Bad reverse sig payload: key ID " + a + " != " + b);
                  }
                  if ((a = payload.uid) !== (b = _this.user.local.uid)) {
                    err = new Error("Bad reverse sig in payload; uid mismatch: " + a + " != " + b);
                  }
                  return __iced_k((a = payload.username) !== (b = _this.user.local.username) ? err = new Error("Bad reverse sig in payload; unsername mismatch: " + a + " != " + b) : void 0);
                });
              });
            } else {
              return __iced_k();
            }
          })(function() {
            return cb(err);
          });
        };
      })(this));
    };

    function SubkeyBase(obj) {
      this.device = obj.device;
      SubkeyBase.__super__.constructor.call(this, obj);
    }

    return SubkeyBase;

  })(Base);

  exports.Subkey = Subkey = (function(_super) {
    __extends(Subkey, _super);

    Subkey.prototype.get_field = function() {
      return "subkey";
    };

    Subkey.prototype.get_subkey = function() {
      return this.subkey;
    };

    Subkey.prototype.get_subkm = function() {
      return this.subkm;
    };

    Subkey.prototype.set_subkey = function(s) {
      return this.subkey = s;
    };

    Subkey.prototype._type = function() {
      return constants.sig_types.subkey;
    };

    function Subkey(obj) {
      this.subkey = obj.subkey;
      this.subkm = obj.subkm;
      this.parent_kid = obj.parent_kid;
      Subkey.__super__.constructor.call(this, obj);
    }

    return Subkey;

  })(SubkeyBase);

}).call(this);
