// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Base, Track, bufeq_secure, constants, kbpgp, unix_time, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };



  kbpgp = require('kbpgp');

  Base = require('./base').Base;

  constants = require('./constants').constants;

  _ref = kbpgp.util, bufeq_secure = _ref.bufeq_secure, unix_time = _ref.unix_time;

  Track = (function(_super) {
    __extends(Track, _super);

    function Track(obj) {
      this.tracking = obj.tracking;
    }

    Track.prototype._type = function() {
      return constants.sig_types.track;
    };

    Track.prototype._json = function() {
      var ret;
      ret = Track.__super__._json.call(this, {});
      ret.tracking = this.tracking;
      return ret;
    };

    return Track;

  })(Base);

}).call(this);
