// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Base, UpdateSettings, constants,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base').Base;

  constants = require('./constants').constants;

  exports.UpdateSettings = UpdateSettings = (function(_super) {
    __extends(UpdateSettings, _super);

    function UpdateSettings(obj) {
      this.update_settings = obj.update_settings;
      UpdateSettings.__super__.constructor.call(this, obj);
    }

    UpdateSettings.prototype._type = function() {
      return constants.sig_types.update_settings;
    };

    UpdateSettings.prototype._required_sections = function() {
      return UpdateSettings.__super__._required_sections.call(this).concat(["update_settings"]);
    };

    UpdateSettings.prototype._v_customize_json = function(ret) {
      return ret.body.update_settings = this.update_settings;
    };

    UpdateSettings.prototype._json = function() {
      return UpdateSettings.__super__._json.call(this, {
        expire_in: 24 * 60 * 60
      });
    };

    return UpdateSettings;

  })(Base);

}).call(this);
