// Generated by IcedCoffeeScript 1.7.1-a
(function() {
  var Base, GithubBinding, KeybaseBinding, RemoteBinding, TwitterBinding, WebServiceBinding, constants, iced, __iced_k, __iced_k_noop,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  Base = require('./base').Base;

  constants = require('./constants').constants;

  WebServiceBinding = (function(_super) {
    __extends(WebServiceBinding, _super);

    function WebServiceBinding() {
      return WebServiceBinding.__super__.constructor.apply(this, arguments);
    }

    WebServiceBinding.prototype._json = function() {
      var o, ret;
      ret = WebServiceBinding.__super__._json.call(this, {});
      if ((o = this.service_obj()) != null) {
        ret.body.service = o;
      }
      return ret;
    };

    WebServiceBinding.prototype._service_obj_check = function(x) {
      return !(x != null);
    };

    WebServiceBinding.prototype._type = function() {
      return constants.sig_types.web_service_binding;
    };

    WebServiceBinding.prototype._v_check = function(_arg, cb) {
      var err, json, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      json = _arg.json;
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/proofs/src/web_service.iced",
            funcname: "WebServiceBinding._v_check"
          });
          WebServiceBinding.__super__._v_check.call(_this, {
            json: json
          }, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return err = arguments[0];
              };
            })(),
            lineno: 25
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          var _ref;
          if (typeof err === "undefined" || err === null) {
            err = !_this._service_obj_check(json != null ? (_ref = json.body) != null ? _ref.service : void 0 : void 0) ? new Error("Bad service object found") : void 0;
          }
          return cb(err);
        };
      })(this));
    };

    return WebServiceBinding;

  })(Base);

  RemoteBinding = (function(_super) {
    __extends(RemoteBinding, _super);

    function RemoteBinding() {
      return RemoteBinding.__super__.constructor.apply(this, arguments);
    }

    RemoteBinding.prototype._service_obj_check = function(x) {
      var so;
      so = this.service_obj();
      return (x != null) && (so.username === x.username) && (so.name === x.name);
    };

    RemoteBinding.prototype.service_obj = function() {
      return {
        name: this.service_name(),
        username: this.user.remote
      };
    };

    RemoteBinding.prototype.is_remote_proof = function() {
      return true;
    };

    return RemoteBinding;

  })(WebServiceBinding);

  TwitterBinding = (function(_super) {
    __extends(TwitterBinding, _super);

    function TwitterBinding() {
      return TwitterBinding.__super__.constructor.apply(this, arguments);
    }

    TwitterBinding.prototype.service_name = function() {
      return "twitter";
    };

    TwitterBinding.prototype.proof_type = function() {
      return constants.proof_types.twitter;
    };

    return TwitterBinding;

  })(RemoteBinding);

  KeybaseBinding = (function(_super) {
    __extends(KeybaseBinding, _super);

    function KeybaseBinding() {
      return KeybaseBinding.__super__.constructor.apply(this, arguments);
    }

    KeybaseBinding.prototype._service_obj_check = function(x) {
      return x == null;
    };

    KeybaseBinding.prototype.service_name = function() {
      return "keybase";
    };

    KeybaseBinding.prototype.proof_type = function() {
      return constants.proof_types.keybase;
    };

    KeybaseBinding.prototype.service_obj = function() {
      return null;
    };

    return KeybaseBinding;

  })(WebServiceBinding);

  GithubBinding = (function(_super) {
    __extends(GithubBinding, _super);

    function GithubBinding() {
      return GithubBinding.__super__.constructor.apply(this, arguments);
    }

    GithubBinding.prototype.service_name = function() {
      return "github";
    };

    GithubBinding.prototype.proof_type = function() {
      return constants.proof_types.github;
    };

    return GithubBinding;

  })(RemoteBinding);

  exports.TwitterBinding = TwitterBinding;

  exports.KeybaseBinding = KeybaseBinding;

  exports.GithubBinding = GithubBinding;

}).call(this);
