// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Base, GenericWebSiteBinding, GithubBinding, KeybaseBinding, SocialNetworkBinding, TwitterBinding, WebServiceBinding, cieq, constants, iced, __iced_k, __iced_k_noop, _ref, _ref1, _ref2, _ref3, _ref4,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script/lib/coffee-script/iced').runtime;
  __iced_k = __iced_k_noop = function() {};

  Base = require('./base').Base;

  constants = require('./constants').constants;

  WebServiceBinding = (function(_super) {
    __extends(WebServiceBinding, _super);

    function WebServiceBinding() {
      _ref = WebServiceBinding.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    WebServiceBinding.prototype._json = function() {
      var o, ret;
      ret = WebServiceBinding.__super__._json.call(this, {});
      if ((o = this.service_obj()) != null) {
        ret.body.service = o;
      }
      return ret;
    };

    WebServiceBinding.prototype._service_obj_check = function(x) {
      return !(x != null);
    };

    WebServiceBinding.prototype._type = function() {
      return constants.sig_types.web_service_binding;
    };

    WebServiceBinding.prototype._v_check = function(_arg, cb) {
      var err, json, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      json = _arg.json;
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/web_service.iced",
          funcname: "WebServiceBinding._v_check"
        });
        WebServiceBinding.__super__._v_check.call(_this, {
          json: json
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 25
        }));
        __iced_deferrals._fulfill();
      })(function() {
        var _ref1;
        if (typeof err === "undefined" || err === null) {
          err = !_this._service_obj_check(json != null ? (_ref1 = json.body) != null ? _ref1.service : void 0 : void 0) ? new Error("Bad service object found") : void 0;
        }
        return cb(err);
      });
    };

    return WebServiceBinding;

  })(Base);

  SocialNetworkBinding = (function(_super) {
    __extends(SocialNetworkBinding, _super);

    function SocialNetworkBinding() {
      _ref1 = SocialNetworkBinding.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    SocialNetworkBinding.prototype._service_obj_check = function(x) {
      var so;
      so = this.service_obj();
      return (x != null) && (so.username === x.username) && (so.name === x.name);
    };

    SocialNetworkBinding.prototype.service_obj = function() {
      return {
        name: this.service_name(),
        username: this.user.remote
      };
    };

    SocialNetworkBinding.prototype.is_remote_proof = function() {
      return true;
    };

    return SocialNetworkBinding;

  })(WebServiceBinding);

  cieq = function(a, b) {
    return a.toLowerCase() === b.toLowerCase();
  };

  GenericWebSiteBinding = (function(_super) {
    __extends(GenericWebSiteBinding, _super);

    function GenericWebSiteBinding(args) {
      this.remote_host = args.remote_host;
      GenericWebSiteBinding.__super__.constructor.call(this, args);
    }

    GenericWebSiteBinding.prototype._service_obj_check = function(x) {
      var so;
      so = this.service_obj();
      return (x != null) && cieq(so.procotol, x.protocol) && cieq(so.hostname, x.hostname);
    };

    GenericWebSiteBinding.prototype.service_obj = function() {
      return this.remote_host;
    };

    GenericWebSiteBinding.prototype.is_remote_proof = function() {
      return true;
    };

    GenericWebSiteBinding.prototype.proof_type = function() {
      return constants.proof_types.generic_web_site;
    };

    return GenericWebSiteBinding;

  })(WebServiceBinding);

  TwitterBinding = (function(_super) {
    __extends(TwitterBinding, _super);

    function TwitterBinding() {
      _ref2 = TwitterBinding.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    TwitterBinding.prototype.service_name = function() {
      return "twitter";
    };

    TwitterBinding.prototype.proof_type = function() {
      return constants.proof_types.twitter;
    };

    return TwitterBinding;

  })(SocialNetworkBinding);

  KeybaseBinding = (function(_super) {
    __extends(KeybaseBinding, _super);

    function KeybaseBinding() {
      _ref3 = KeybaseBinding.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    KeybaseBinding.prototype._service_obj_check = function(x) {
      return x == null;
    };

    KeybaseBinding.prototype.service_name = function() {
      return "keybase";
    };

    KeybaseBinding.prototype.proof_type = function() {
      return constants.proof_types.keybase;
    };

    KeybaseBinding.prototype.service_obj = function() {
      return null;
    };

    return KeybaseBinding;

  })(WebServiceBinding);

  GithubBinding = (function(_super) {
    __extends(GithubBinding, _super);

    function GithubBinding() {
      _ref4 = GithubBinding.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    GithubBinding.prototype.service_name = function() {
      return "github";
    };

    GithubBinding.prototype.proof_type = function() {
      return constants.proof_types.github;
    };

    return GithubBinding;

  })(SocialNetworkBinding);

  exports.TwitterBinding = TwitterBinding;

  exports.KeybaseBinding = KeybaseBinding;

  exports.GithubBinding = GithubBinding;

}).call(this);
